### ISSUE TITLE
[BUG 🐞] GoogleMap widget listen/respond to touches even if there is another widget/dialog on top of it

### ISSUE THREAD

**Issue by ramioooz** [marchdev-tk/flutter_google_maps#37] opened 2020-06-04 08:19 UTC
## Steps to Reproduce

1. Put GoogleMap widget in a stack`.
2. put a small container in the stack together with the map widget to block clicks from reaching map widget at the area covered by the container

**Expected results:** 
Clicks on container area should not be sent to map widget

**Actual results:** 
map widget listens/responds to clicks on the container blocking it. which is not what we are expecting

<details>
  <summary>Code</summary>

```
Stack(
   children: <Widget>[
       _mapWidget(),
       mapOverlay(),
   ],
)

_mapWidget() {
    var _loc = GeoCoord(
      14.659334,
      31.542844,
    );
    var _zoom = 11.0;

    return new GoogleMap(
      key: mapKey_newJob,
      // markers: markers,
      minZoom: 11, // how far camera is
      maxZoom: 18, // how close camara is
      initialPosition: _loc,
      initialZoom: _zoom,
      mapType: MapType.roadmap,
      mobilePreferences: MobileMapPreferences(
        tiltGesturesEnabled: false,
        rotateGesturesEnabled: false,
        mapToolbarEnabled: false,
        myLocationEnabled: false,
      ),
      webPreferences: WebMapPreferences(
        // fullscreenControl: false,
        mapTypeControl: false,
        rotateControl: false,
        streetViewControl: false,
        zoomControl: true,
        // overviewMapControl: false,
      ),
      onTap: (tapLoc) async {
        if (isFetchingAddress) {
          return;
        }
        GoogleMap.of(mapKey_newJob).clearMarkers();
        GoogleMap.of(mapKey_newJob).addMarkerRaw(
          tapLoc,
          icon: 'assets/imgs/requesterLocation_01.png',
          info: 'Lat:${tapLoc.latitude}, Lng:${tapLoc.latitude}',
        );
      },
    );
  }

  mapOverlay() {
    return Padding(
        padding: const EdgeInsets.all(10),
        child: Stack(
          children: <Widget>[
            // pickLocationTxtWgt(),
            // removeLocationBtn(),
            searchDisplayAddressWgt(),
          ],
        ),
      );
  }
```

</details>

**Comment by randomdude583** [comment] 2020-06-04 08:25
This looks to be the same as #23

**Comment by march-dev** [comment] 2020-06-22 12:39
Duplicate of [#23](https://github.com/marchdev-tk/flutter_google_maps/issues/23)

**Closed by march-dev** 2020-06-22 12:39 UTC
Labels: duplicate, platform-web
